# Match alacritty setup

# Font
font_family      JetBrains Mono
font_size        8

# Transparency
background_opacity 0.75

# Hide title bar / window decorations
hide_window_decorations yes

# No confirm on close
confirm_os_window_close 0
